/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tugaspraktikum92;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {

    private Scene homeScene;
    private Scene addProfilScene;
    private Scene profileScene;
    
    // Labels to be updated in profile scene
    private Label usernameLabel;
    private Label birthdayLabel;
    private Label addressLabel;

    @Override
    public void start(Stage primaryStage) {
        // Home Scene
        Label homeLabel = new Label("Hello,\nPrecious People!");
        homeLabel.setStyle("-fx-font-size: 40px; -fx-font-weight: bold; -fx-font-family: 'cooper black'");

        Button addProfileButton = new Button("Add Profile");
        addProfileButton.setOnAction(e -> primaryStage.setScene(addProfilScene));

        Button goToProfileButton = new Button("Go to Profile");
        goToProfileButton.setOnAction(e -> primaryStage.setScene(profileScene));

        VBox homeLayout = new VBox(30);
        homeLayout.getChildren().addAll(homeLabel, addProfileButton, goToProfileButton);
        homeLayout.setAlignment(Pos.CENTER);
        homeLayout.setStyle("-fx-background-color:linear-gradient(to bottom, #535C91,#FEFDED);");
        
        homeScene = new Scene(homeLayout, 600, 500);
        

        // Add Profile Scene
        Label userTitle = new Label("Profile");
        userTitle.setStyle("-fx-font-size: 35px; -fx-font-weight: bold;");
        // Username input
        Label userNameLabel = new Label("Username ");
        userNameLabel.setStyle("-fx-font-size: 15px; -fx-font-weight: bold;");
        // Birthday input
        Label birthdayInputLabel = new Label("Birthday  ");
        birthdayInputLabel.setStyle("-fx-font-size: 15px; -fx-font-weight: bold;");
        // Address Input
        Label addressInputLabel = new Label("Address    ");
        addressInputLabel.setStyle("-fx-font-size: 15px; -fx-font-weight: bold;");
        
        VBox data = new VBox(15);
        data.getChildren().addAll(userNameLabel, birthdayInputLabel, addressInputLabel);

        //penggabungan textfieldnyaa
        TextField usernametextField = new TextField();
        usernametextField.setPrefWidth(200);
        TextField birthdaytextField = new TextField();
        birthdaytextField.setPrefWidth(200);
        TextField addresstextField = new TextField();
        addresstextField.setPrefWidth(200);

        VBox input = new VBox(10);
        input.getChildren().addAll(usernametextField,birthdaytextField,addresstextField);

        HBox result = new HBox(10);
        result.getChildren().addAll(data,input);
        result.setAlignment(Pos.CENTER);

        // Buttons
        Button backButton = new Button("Back to Home");
        backButton.setOnAction(e -> primaryStage.setScene(homeScene));
        
        Button saveButton = new Button("Save");
        saveButton.setOnAction(e -> {
            String nama = usernametextField.getText();
            String birthday = birthdaytextField.getText();
            String address = addresstextField.getText();
            
            if (!nama.isEmpty() && !birthday.isEmpty() && !address.isEmpty()) {
                // Update the labels in the profile scene
                usernameLabel.setText("Username: " + nama);
                usernameLabel.setStyle("-fx-font-size: 15px;");
                birthdayLabel.setText("Birthday: " + birthday);
                birthdayLabel.setStyle("-fx-font-size: 15px;");
                addressLabel.setText("Address  : " + address);
                addressLabel.setStyle("-fx-font-size: 15px;");

                // Switch to profile scene
                primaryStage.setScene(profileScene);
            }
        });
        
        HBox button = new HBox(165, backButton, saveButton);
        button.setAlignment(Pos.CENTER);
        
        VBox addprofileLayout = new VBox(20, userTitle, result, button);
        addprofileLayout.setAlignment(Pos.CENTER);
        // backButton.relocate(100, 200);
        addprofileLayout.setStyle("-fx-background-color:linear-gradient(to bottom, #535C91, #FEFDED);");
        addProfilScene = new Scene(addprofileLayout, 600, 500);
        
        // Profile Scene
        Label profileLabel = new Label("Profile");
        profileLabel.setStyle("-fx-font-size: 30px; -fx-font-weight: bold;");
        usernameLabel = new Label();
        birthdayLabel = new Label();
        addressLabel = new Label();
        
        Button backButton2 = new Button("Back to Home");
        backButton2.setOnAction(e -> primaryStage.setScene(homeScene));

        VBox profileLayout = new VBox(20);
        profileLayout.getChildren().addAll(profileLabel, usernameLabel, birthdayLabel, addressLabel, backButton2);
        profileLayout.setAlignment(Pos.CENTER);
        profileLayout.setStyle("-fx-background-color: linear-gradient(to bottom, #535C91, #FFFFFF);");
        profileScene = new Scene(profileLayout, 600, 500);

        // Setting the initial scene
        primaryStage.setScene(homeScene);
        primaryStage.setTitle("Simple JavaFX App");
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
