/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.yusra.main;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage stage) throws Exception {
        stage.setTitle("Tuprak ni boss");
        stage.setResizable(true);

        LoginPage init = new LoginPage(stage);
        init.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}