/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.yusra.main;

import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.shape.Rectangle;
import javafx.scene.text.Font;
import javafx.stage.Screen;
import javafx.stage.Stage;

public class LoginPage {
    private Stage stage;
    public static final String nama = "Yusra";
    public static final String password = "123";

    LoginPage(Stage stage){
        this.stage = stage;
    }
    public void show() throws Exception {
        StackPane root = new StackPane();
        Scene scene = new Scene(root, 1366, 700);
        Image pic = new Image("file:src/main/resources/pic/bgpeace1.png");
        ImageView bg = new ImageView(pic);
        Rectangle kotak = new Rectangle(400, 550);
        TextField username = new TextField("");
        PasswordField pass = new PasswordField();
        Button loginbtn = new Button("Sign Up");
        Button masuk = new Button("Masuk");
        Label login = new Label("LOGIN");
        Label or = new Label("OR");
        VBox center = new VBox(20);
        
        scene.getStylesheets().add(getClass().getResource("/style/style.css").toExternalForm());
        Font.loadFont(getClass().getResourceAsStream("/font/BebasNeueBold.otf"), 12);

        bg.setFitWidth(1366);
        bg.setFitHeight(768);
        kotak.setStyle("-fx-fill : #000;");
        kotak.setOpacity(0.75);

        login.getStyleClass().add("login");
        username.getStyleClass().add("username");
        pass.getStyleClass().add("password");
        masuk.getStyleClass().add("masuk");
        loginbtn.getStyleClass().add("new");
        or.getStyleClass().add("or");
        username.setPromptText("Username");
        pass.setPromptText("Password");

        username.setAlignment(Pos.CENTER_LEFT);
        username.setFocusTraversable(false);
        pass.setFocusTraversable(false);
        center.getChildren().addAll(login, username, pass, masuk, or, loginbtn);
        center.setAlignment(Pos.CENTER);
        center.setMaxWidth(350);
        center.setMaxHeight(600);
        root.getChildren().addAll(bg, kotak, center);
        StackPane.setAlignment(kotak, Pos.CENTER);

        masuk.setOnAction(e ->{
            if(username.getText().equals(nama) && pass.getText().equals(password)){
                Profile pro = new Profile(stage);
                pro.show();
                
            }
        });
        
        double screenWidth = Screen.getPrimary().getVisualBounds().getWidth();
        double screenHeight = Screen.getPrimary().getVisualBounds().getHeight();
        root.setPrefSize(screenWidth, screenHeight);
        stage.setScene(scene);
        stage.show();

    }

    public static void main(String[] args) {
    }
}