/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package praktikum_kiki;

import javafx.application.Application;
import javafx.scene.Scene;
// import javafx.scene.control.Label;
import javafx.scene.layout.Pane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        stage.setTitle("Aplikasi sederhana");
        Pane root = new Pane();
        root.getStyleClass().add("latar");
        Scene scene = new Scene(root, 640, 480);
        scene.getStylesheets().add(getClass().getResource("/style/Style.css").toExternalForm());
        stage.setScene(scene);
        stage.show();

        Home home = new Home(stage);
        home.show();
    }

    public static void main(String[] args) {
        launch();
    }
}




// import javafx.application.Application;
// import javafx.scene.Scene;
// import javafx.scene.layout.Pane;
// import javafx.stage.Stage;

// public class App extends Application {

//     public void start (Stage stage) {

//         stage.setTitle("Aplikasi Sederhana");
//         Pane root = new Pane();
//         Scene scene = new Scene(root, 640,600);
//         stage.setScene(scene);
//         stage.show();
//         Home home = new Home(stage);
//         home.show();
        
//     }

//     public static void main(String[] args) {
//         launch();
//     }

// }
